### ISSUE TITLE
User-defined training images?

### ISSUE THREAD

**Issue by stanbiryukov** [juliohm/GeoStatsImages.jl#3]
Hi, 
Is there a method to create and use custom training images for the image quilting solver?  Ie:
`TI = training_image("my_img_path.jpg")`
Thanks!

**Comment by juliohm** [comment]
Hi @stanbiryukov , thanks for reaching out. The training images for the image quilting solver can be any 3D Julia array. In that case, you would have to load the image from disk, and convert it to an `Array{Float64}`. Maybe we could add a function for this in the future. Please let me know if you have any issues. The general method to load images in Julia is:

```julia
using Images

img = load("img.jpg")
gimg = Gray.(img) # convert to grayscale (single channel)
TI = Float64.(gimg) # convert to a simple array of floats for image quilting
```

Please feel free to reach out in our gitter channel if you have more questions: https://gitter.im/JuliaEarth/GeoStats.jl

**Comment by stanbiryukov** [comment]
Excellent - thanks for the quick reply, @juliohm!
